/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary":                   "#021541",
        "on-primary":                "#ffffff",
        "primary-container":         "#1a2b56",
        "on-primary-container":      "#8393c5",
        "primary-fixed":             "#dae1ff",
        "primary-fixed-dim":         "#b5c5f9",
        "on-primary-fixed":          "#051944",
        "on-primary-fixed-variant":  "#354572",
        "inverse-primary":           "#b5c5f9",
        "secondary":                 "#8f4e00",
        "on-secondary":              "#ffffff",
        "secondary-container":       "#fe9832",
        "on-secondary-container":    "#683700",
        "secondary-fixed":           "#ffdcc2",
        "secondary-fixed-dim":       "#ffb77a",
        "on-secondary-fixed":        "#2e1500",
        "on-secondary-fixed-variant":"#6d3a00",
        "tertiary":                  "#291300",
        "on-tertiary":               "#ffffff",
        "tertiary-container":        "#472400",
        "on-tertiary-container":     "#bf895b",
        "tertiary-fixed":            "#ffdcc1",
        "tertiary-fixed-dim":        "#f6ba88",
        "on-tertiary-fixed":         "#2e1500",
        "on-tertiary-fixed-variant": "#663d16",
        "surface":                   "#fbf8fd",
        "surface-dim":               "#F8F9FA",
        "surface-bright":            "#fbf8fd",
        "surface-container-lowest":  "#ffffff",
        "surface-container-low":     "#f5f3f7",
        "surface-container":         "#efedf1",
        "surface-container-high":    "#e9e7ec",
        "surface-container-highest": "#e4e2e6",
        "surface-variant":           "#e4e2e6",
        "surface-tint":              "#4d5d8b",
        "on-surface":                "#1b1b1f",
        "on-surface-variant":        "#45464f",
        "inverse-surface":           "#303034",
        "inverse-on-surface":        "#f2f0f4",
        "outline":                   "#757680",
        "outline-variant":           "#c5c6d0",
        "background":                "#fbf8fd",
        "on-background":             "#1b1b1f",
        "error":                     "#D32F2F",
        "on-error":                  "#ffffff",
        "error-container":           "#ffdad6",
        "on-error-container":        "#93000a",
        "success":                   "#28A745",
        "warning":                   "#FFC107",
        "info":                      "#17A2B8",
        "ash-gray":                  "#6C757D",
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "sm": "0.125rem",
        "md": "0.25rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
        "pill": "9999px",
      },
      spacing: {
        "margin-mobile":  "16px",
        "gutter":         "24px",
        "base":           "8px",
        "margin-desktop": "64px",
        "container-max":  "1200px",
      },
      maxWidth: {
        "container-max":  "1200px",
        "container-narrow": "960px",
      },
      fontFamily: {
        "sans":               ["Inter", "Noto Sans", "system-ui", "sans-serif"],
        "display-lg":         ["Inter", "sans-serif"],
        "headline-lg":        ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "headline-md":        ["Inter", "sans-serif"],
        "body-lg":            ["Inter", "sans-serif"],
        "body-md":            ["Inter", "sans-serif"],
        "label-md":           ["Noto Sans", "sans-serif"],
        "label-sm":           ["Noto Sans", "sans-serif"],
        "bengali-body":       ["Noto Sans Bengali", "Noto Sans", "sans-serif"],
      },
      fontSize: {
        "display-lg":         ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg":        ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-md":        ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-lg":            ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md":            ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-md":           ["14px", { lineHeight: "1.4", fontWeight: "500" }],
        "label-sm":           ["12px", { lineHeight: "1.2", fontWeight: "500" }],
        "bengali-body":       ["16px", { lineHeight: "1.8", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
}